# Generated by Django 4.1.11 on 2023-09-21 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.URLField(blank=True, max_length=250, null=True)),
                ('appearances', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('image', models.URLField(blank=True, max_length=250, null=True)),
                ('onSaleDate', models.DateField()),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comics',
            },
        ),
    ]
