# Generated by Django 4.1.11 on 2023-09-20 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterios', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'busqueda',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.URLField(blank=True, max_length=250, null=True)),
                ('appearances', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'personajes',
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.URLField(max_length=250)),
                ('onSaleDate', models.DateField()),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.personaje')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comics',
            },
        ),
    ]
