# Generated by Django 4.1.11 on 2023-09-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.URLField(max_length=250)),
                ('onSaleDate', models.DateField()),
            ],
            options={
                'db_table': 'comics',
            },
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaje', models.CharField(max_length=200)),
                ('comic', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'filtross',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.URLField(max_length=250)),
                ('appearances', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'personajes',
            },
        ),
    ]
