# Generated by Django 4.1.11 on 2023-09-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='personaje',
        ),
    ]
