# Generated by Django 4.1.11 on 2023-09-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comic')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.personaje')),
            ],
            options={
                'db_table': 'busqueda',
            },
        ),
    ]
